# Linear Algebra

## Matrix dot product

In [1]:
import numpy as np
from math import sqrt

U = np.matrix([[1/sqrt(2)+1j/2, -1j/2], 
              [1/2, 1/2+1j/sqrt(2)]])
X = np.matrix([[0,1],[1,0]])
Y = np.matrix([[0,-1j],[1j,0]])
Z = np.matrix([[1,0],[0,-1]])
# U.getH()
np.matmul(U,X)
print(np.matmul(U,X,U.H))
print(np.matmul(np.dot(U,X),U.getH()))
print(np.matmul(np.matmul(U,X),U.H))
print(np.dot(np.dot(U,X),U.getH()))
print(np.dot(np.dot(U,Y),U.getH()))
print(np.dot(np.dot(U,Z),U.getH()))

[[0.        -0.5j        0.70710678+0.5j       ]
 [0.5       +0.70710678j 0.5       +0.j        ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[ 7.07106781e-01+0.j          1.11022302e-16-0.70710678j]
 [ 1.11022302e-16+0.70710678j -7.07106781e-01+0.j        ]]
[[ 0.5       +0.j   0.70710678+0.5j]
 [ 0.70710678-0.5j -0.5       +0.j ]]


In [2]:
print(np.matmul(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [3]:
print(np.dot(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


## Matrix exponentiation

In [4]:
from scipy.linalg import expm, sinm, cosm
import numpy as np
# hadmard gate
h = np.array([[1.0, 1.0], [1.0, -1.0]])
expm(1j*h/np.sqrt(2)*np.pi/2)

array([[ 3.23420673e-17+0.70710678j,  3.23420673e-17+0.70710678j],
       [-3.58447001e-18+0.70710678j,  4.67208659e-17-0.70710678j]])

## Solve matrix inverse

In [5]:
## solve A(4,3)*B(3,2)=C(4,2)
import numpy as np
from numpy.linalg import inv, matrix_rank, det
from numpy import dot, transpose
# np.set_printoptions(precision=5)

A = np.random.randn(4, 3)
C = np.random.randn(4, 2)
print(matrix_rank(A))
print('A=',A)
print('C=',C)
AT_A = dot(transpose(A),A)
print('AT_A=',AT_A)
print('rank of AT_A:',matrix_rank(AT_A))
A_left_inverse = dot(inv( AT_A ), transpose(A))
print(dot(inv( AT_A ), AT_A ))
print(dot(A,A_left_inverse))
B = dot(A_left_inverse, C)
print('B=',B)
# print(dot(A,dot(A_left_inverse, C)))
print('A*B=',dot(A,B))

3
A= [[ 2.38983204  0.57122736 -0.3292307 ]
 [-0.30772097 -0.47422035 -0.14130302]
 [-1.23202667 -0.35802384 -1.18053201]
 [ 1.59610196  0.94861975 -1.01378141]]
C= [[-0.5490913   0.51609507]
 [ 0.01208208 -0.97180994]
 [-1.81254681 -1.81484047]
 [ 0.32115655 -1.12426955]]
AT_A= [[ 9.87142057  3.46625377 -0.90697576]
 [ 3.46625377  1.57924614 -0.66009127]
 [-0.90697576 -0.66009127  2.54976796]]
rank of AT_A: 3
[[ 1.00000000e+00  2.77555756e-17  0.00000000e+00]
 [-7.77156117e-16  1.00000000e+00  2.22044605e-16]
 [-5.55111512e-17  0.00000000e+00  1.00000000e+00]]
[[ 0.83809361  0.28350338 -0.14667298  0.18386293]
 [ 0.28350338  0.5035763   0.25682919 -0.32195001]
 [-0.14667298  0.25682919  0.86712714  0.16656368]
 [ 0.18386293 -0.32195001  0.16656368  0.79120294]]
B= [[-0.23445562  0.19768485]
 [ 1.35466625  0.38440456]
 [ 1.04904262  1.44432109]]
A*B= [[-0.13186417  0.21650115]
 [-0.71849628 -0.44721118]
 [-1.43457563 -2.08624628]
 [-0.15265182 -0.78404693]]


In [6]:
a = np.array([[1., 2., 3.], [3., 5., 3.]])
aT_a = dot(transpose(a),a)
print(aT_a)
print(det(aT_a))
print('rank:',matrix_rank(aT_a))
ainv = inv(aT_a)
print(ainv)
np.allclose(dot(ainv, aT_a), np.eye(3))

[[10. 17. 12.]
 [17. 29. 21.]
 [12. 21. 18.]]
-2.498001805406606e-14
rank: 2
[[-3.24259173e+15  2.16172782e+15 -3.60287970e+14]
 [ 2.16172782e+15 -1.44115188e+15  2.40191980e+14]
 [-3.60287970e+14  2.40191980e+14 -4.00319967e+13]]


False