# Linear Algebra

## Matrix dot product

In [1]:
import numpy as np
from math import sqrt

U = np.matrix([[1/sqrt(2)+1j/2, -1j/2], 
              [1/2, 1/2+1j/sqrt(2)]])
X = np.matrix([[0,1],[1,0]])
Y = np.matrix([[0,-1j],[1j,0]])
Z = np.matrix([[1,0],[0,-1]])
# U.getH()
np.matmul(U,X)
print(np.matmul(U,X,U.H))
print(np.matmul(np.dot(U,X),U.getH()))
print(np.matmul(np.matmul(U,X),U.H))
print(np.dot(np.dot(U,X),U.getH()))
print(np.dot(np.dot(U,Y),U.getH()))
print(np.dot(np.dot(U,Z),U.getH()))

[[0.        -0.5j        0.70710678+0.5j       ]
 [0.5       +0.70710678j 0.5       +0.j        ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[ 7.07106781e-01+0.j          1.11022302e-16-0.70710678j]
 [ 1.11022302e-16+0.70710678j -7.07106781e-01+0.j        ]]
[[ 0.5       +0.j   0.70710678+0.5j]
 [ 0.70710678-0.5j -0.5       +0.j ]]


In [2]:
print(np.matmul(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [3]:
print(np.dot(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


## Matrix exponentiation

In [4]:
from scipy.linalg import expm, sinm, cosm
import numpy as np
# hadmard gate
h = np.array([[1.0, 1.0], [1.0, -1.0]])
expm(1j*h/np.sqrt(2)*np.pi/2)

array([[6.123234e-17+0.70710678j, 0.000000e+00+0.70710678j],
       [0.000000e+00+0.70710678j, 6.123234e-17-0.70710678j]])

## Solve matrix inverse

In [5]:
## solve A(4,3)*B(3,2)=C(4,2)
import numpy as np
from numpy.linalg import inv, matrix_rank, det
from numpy import dot, transpose
# np.set_printoptions(precision=5)

A = np.random.randn(4, 3)
C = np.random.randn(4, 2)
print(matrix_rank(A))
print('A=',A)
print('C=',C)
AT_A = dot(transpose(A),A)
print('AT_A=',AT_A)
print('rank of AT_A:',matrix_rank(AT_A))
A_left_inverse = dot(inv( AT_A ), transpose(A))
print(dot(inv( AT_A ), AT_A ))
print(dot(A,A_left_inverse))
B = dot(A_left_inverse, C)
print('B=',B)
# print(dot(A,dot(A_left_inverse, C)))
print('A*B=',dot(A,B))

3
A= [[ 1.70951333  0.02669562  0.56647952]
 [-1.50150471  0.22502004 -0.38519427]
 [ 0.2466312   1.08770668 -0.61499135]
 [-1.34633434 -0.88231908 -1.49497462]]
C= [[-0.99894252 -0.50938036]
 [-0.02750832  0.39120279]
 [ 0.29892499  1.94723709]
 [-0.11906095  0.94543227]]
AT_A= [[7.05039533 1.16392677 3.40783492]
 [1.16392677 2.01293945 0.57856054]
 [3.40783492 0.57856054 3.08243715]]
rank of AT_A: 3
[[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.67361738e-17 1.00000000e+00 4.16333634e-17]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
[[ 0.49659685 -0.49081649  0.04629611 -0.08333223]
 [-0.49081649  0.52145546  0.04513856 -0.08124867]
 [ 0.04629611  0.04513856  0.99574232  0.00766375]
 [-0.08333223 -0.08124867  0.00766375  0.98620537]]
B= [[-0.30282484  0.18792367]
 [ 0.34732375  0.96214569]
 [ 0.08756111 -1.37788575]]
A*B= [[-0.4588095  -0.43360095]
 [ 0.49911968  0.46508748]
 [ 0.24925098  1.94026795]
 [-0.02964853  0.95797663]]


In [6]:
a = np.array([[1., 2., 3.], [3., 5., 3.]])
aT_a = dot(transpose(a),a)
print(aT_a)
print(det(aT_a))
print('rank:',matrix_rank(aT_a))
ainv = inv(aT_a)
print(ainv)
np.allclose(dot(ainv, aT_a), np.eye(3))

[[10. 17. 12.]
 [17. 29. 21.]
 [12. 21. 18.]]
-3.197442310920468e-14
rank: 2
[[-2.53327479e+15  1.68884986e+15 -2.81474977e+14]
 [ 1.68884986e+15 -1.12589991e+15  1.87649984e+14]
 [-2.81474977e+14  1.87649984e+14 -3.12749974e+13]]


False