# Linear Algebra

### Perron–Frobenius theorem

````{prf:theorem} Perron–Frobenius theorem
:label: perron_frobenius_theorem
<!-- :class: dropdown -->

a real square matrix with positive entries has a unique largest real eigenvalue and that the corresponding eigenvector can be chosen to have strictly positive components, and also asserts a similar statement for certain classes of nonnegative matrices. 
````

## Matrix dot product

In [1]:
import numpy as np
from math import sqrt

U = np.matrix([[1/sqrt(2)+1j/2, -1j/2], 
              [1/2, 1/2+1j/sqrt(2)]])
X = np.matrix([[0,1],[1,0]])
Y = np.matrix([[0,-1j],[1j,0]])
Z = np.matrix([[1,0],[0,-1]])
# U.getH()
np.matmul(U,X)
print(np.matmul(U,X,U.H))
print(np.matmul(np.dot(U,X),U.getH()))
print(np.matmul(np.matmul(U,X),U.H))
print(np.dot(np.dot(U,X),U.getH()))
print(np.dot(np.dot(U,Y),U.getH()))
print(np.dot(np.dot(U,Z),U.getH()))

[[0.        -0.5j        0.70710678+0.5j       ]
 [0.5       +0.70710678j 0.5       +0.j        ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[ 7.07106781e-01+0.j          1.11022302e-16-0.70710678j]
 [ 1.11022302e-16+0.70710678j -7.07106781e-01+0.j        ]]
[[ 0.5       +0.j   0.70710678+0.5j]
 [ 0.70710678-0.5j -0.5       +0.j ]]


In [2]:
print(np.matmul(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [3]:
print(np.dot(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


## Matrix exponentiation

In [4]:
from scipy.linalg import expm, sinm, cosm
import numpy as np
# hadmard gate
h = np.array([[1.0, 1.0], [1.0, -1.0]])
expm(1j*h/np.sqrt(2)*np.pi/2)

array([[6.123234e-17+0.70710678j, 0.000000e+00+0.70710678j],
       [0.000000e+00+0.70710678j, 6.123234e-17-0.70710678j]])

## Solve matrix inverse

In [5]:
## solve A(4,3)*B(3,2)=C(4,2)
import numpy as np
from numpy.linalg import inv, matrix_rank, det
from numpy import dot, transpose
# np.set_printoptions(precision=5)

A = np.random.randn(4, 3)
C = np.random.randn(4, 2)
print(matrix_rank(A))
print('A=',A)
print('C=',C)
AT_A = dot(transpose(A),A)
print('AT_A=',AT_A)
print('rank of AT_A:',matrix_rank(AT_A))
A_left_inverse = dot(inv( AT_A ), transpose(A))
print(dot(inv( AT_A ), AT_A ))
print(dot(A,A_left_inverse))
B = dot(A_left_inverse, C)
print('B=',B)
# print(dot(A,dot(A_left_inverse, C)))
print('A*B=',dot(A,B))

3
A= [[ 0.43166776  0.0581599  -0.28352453]
 [-1.1103126   0.39609683 -0.77133235]
 [ 0.33932321 -0.40806154 -0.31301203]
 [ 0.09002919  0.56446735  0.81392403]]
C= [[ 1.50660669  0.60454638]
 [ 0.55401181  1.31789622]
 [-0.88931193 -0.90421449]
 [-0.10227877 -0.55975846]]
AT_A= [[ 1.54237661 -0.50233177  0.7010963 ]
 [-0.50233177  0.64541289  0.26514966]
 [ 0.7010963   0.26514966  1.43578861]]
rank of AT_A: 3
[[ 1.00000000e+00 -2.77555756e-16 -2.22044605e-16]
 [-4.44089210e-16  1.00000000e+00 -4.44089210e-16]
 [ 2.22044605e-16  1.11022302e-16  1.00000000e+00]]
[[ 0.966151    0.0408036   0.15375629  0.08600764]
 [ 0.0408036   0.9508129  -0.185347   -0.10367874]
 [ 0.15375629 -0.185347    0.30157473 -0.39068261]
 [ 0.08600764 -0.10367874 -0.39068261  0.78146136]]
B= [[ 1.55194417  0.03260702]
 [ 2.87455358  1.47881288]
 [-1.7479023  -1.23658729]]
A*B= [[ 1.33268117  0.45068583]
 [ 0.76367199  1.50336889]
 [-0.09926964 -0.20531565]
 [ 0.33965225 -0.16881094]]


In [6]:
a = np.array([[1., 2., 3.], [3., 5., 3.]])
aT_a = dot(transpose(a),a)
print(aT_a)
print(det(aT_a))
print('rank:',matrix_rank(aT_a))
ainv = inv(aT_a)
print(ainv)
np.allclose(dot(ainv, aT_a), np.eye(3))

[[10. 17. 12.]
 [17. 29. 21.]
 [12. 21. 18.]]
-3.197442310920468e-14
rank: 2
[[-2.53327479e+15  1.68884986e+15 -2.81474977e+14]
 [ 1.68884986e+15 -1.12589991e+15  1.87649984e+14]
 [-2.81474977e+14  1.87649984e+14 -3.12749974e+13]]


False