# Linear Algebra

## Matrix dot product

In [1]:
import numpy as np
from math import sqrt

U = np.matrix([[1/sqrt(2)+1j/2, -1j/2], 
              [1/2, 1/2+1j/sqrt(2)]])
X = np.matrix([[0,1],[1,0]])
Y = np.matrix([[0,-1j],[1j,0]])
Z = np.matrix([[1,0],[0,-1]])
# U.getH()
np.matmul(U,X)
print(np.matmul(U,X,U.H))
print(np.matmul(np.dot(U,X),U.getH()))
print(np.matmul(np.matmul(U,X),U.H))
print(np.dot(np.dot(U,X),U.getH()))
print(np.dot(np.dot(U,Y),U.getH()))
print(np.dot(np.dot(U,Z),U.getH()))

[[0.        -0.5j        0.70710678+0.5j       ]
 [0.5       +0.70710678j 0.5       +0.j        ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[ 7.07106781e-01+0.j          1.11022302e-16-0.70710678j]
 [ 1.11022302e-16+0.70710678j -7.07106781e-01+0.j        ]]
[[ 0.5       +0.j   0.70710678+0.5j]
 [ 0.70710678-0.5j -0.5       +0.j ]]


In [2]:
print(np.matmul(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [3]:
print(np.dot(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


## Matrix exponentiation

In [4]:
from scipy.linalg import expm, sinm, cosm
import numpy as np
# hadmard gate
h = np.array([[1.0, 1.0], [1.0, -1.0]])
expm(1j*h/np.sqrt(2)*np.pi/2)

array([[6.123234e-17+0.70710678j, 0.000000e+00+0.70710678j],
       [0.000000e+00+0.70710678j, 6.123234e-17-0.70710678j]])

## Solve matrix inverse

In [5]:
## solve A(4,3)*B(3,2)=C(4,2)
import numpy as np
from numpy.linalg import inv, matrix_rank, det
from numpy import dot, transpose
# np.set_printoptions(precision=5)

A = np.random.randn(4, 3)
C = np.random.randn(4, 2)
print(matrix_rank(A))
print('A=',A)
print('C=',C)
AT_A = dot(transpose(A),A)
print('AT_A=',AT_A)
print('rank of AT_A:',matrix_rank(AT_A))
A_left_inverse = dot(inv( AT_A ), transpose(A))
print(dot(inv( AT_A ), AT_A ))
print(dot(A,A_left_inverse))
B = dot(A_left_inverse, C)
print('B=',B)
# print(dot(A,dot(A_left_inverse, C)))
print('A*B=',dot(A,B))

3
A= [[-0.09817149  0.33201712 -0.2904607 ]
 [ 0.06313421  2.06871144  0.78344587]
 [-1.21548836  1.01727506 -2.0225844 ]
 [ 1.14484675  1.22248659 -0.90393535]]
C= [[ 0.98670536 -1.4890267 ]
 [-0.68922908 -1.0879725 ]
 [ 0.66926732 -0.96574028]
 [-0.01190626  0.46536899]]
AT_A= [[ 2.8017096   0.26108565  1.50153755]
 [ 0.26108565  6.91912438 -1.63828801]
 [ 1.50153755 -1.63828801  5.60610161]]
rank of AT_A: 3
[[ 1.00000000e+00  5.55111512e-17 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 0.02549258  0.05563398  0.13578556  0.05753129]
 [ 0.05563398  0.99682389 -0.00775191 -0.00328442]
 [ 0.13578556 -0.00775191  0.98107996 -0.00801627]
 [ 0.05753129 -0.00328442 -0.00801627  0.99660357]]
B= [[-0.11646058  0.7721102 ]
 [-0.15285136 -0.5238527 ]
 [-0.40045735 -0.16139739]]
A*B= [[ 0.07700096 -0.20284767]
 [-0.63729466 -1.16139961]
 [ 0.79602338 -1.14495342]
 [ 0.0417993   0.38943776]]


In [6]:
a = np.array([[1., 2., 3.], [3., 5., 3.]])
aT_a = dot(transpose(a),a)
print(aT_a)
print(det(aT_a))
print('rank:',matrix_rank(aT_a))
ainv = inv(aT_a)
print(ainv)
np.allclose(dot(ainv, aT_a), np.eye(3))

[[10. 17. 12.]
 [17. 29. 21.]
 [12. 21. 18.]]
-3.197442310920468e-14
rank: 2
[[-2.53327479e+15  1.68884986e+15 -2.81474977e+14]
 [ 1.68884986e+15 -1.12589991e+15  1.87649984e+14]
 [-2.81474977e+14  1.87649984e+14 -3.12749974e+13]]


False