# Linear Algebra

## Matrix dot product

In [1]:
import numpy as np
from math import sqrt

U = np.matrix([[1/sqrt(2)+1j/2, -1j/2], 
              [1/2, 1/2+1j/sqrt(2)]])
X = np.matrix([[0,1],[1,0]])
Y = np.matrix([[0,-1j],[1j,0]])
Z = np.matrix([[1,0],[0,-1]])
# U.getH()
np.matmul(U,X)
print(np.matmul(U,X,U.H))
print(np.matmul(np.dot(U,X),U.getH()))
print(np.matmul(np.matmul(U,X),U.H))
print(np.dot(np.dot(U,X),U.getH()))
print(np.dot(np.dot(U,Y),U.getH()))
print(np.dot(np.dot(U,Z),U.getH()))

[[0.        -0.5j        0.70710678+0.5j       ]
 [0.5       +0.70710678j 0.5       +0.j        ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[ 7.07106781e-01+0.j          1.11022302e-16-0.70710678j]
 [ 1.11022302e-16+0.70710678j -7.07106781e-01+0.j        ]]
[[ 0.5       +0.j   0.70710678+0.5j]
 [ 0.70710678-0.5j -0.5       +0.j ]]


In [2]:
print(np.matmul(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [3]:
print(np.dot(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


## Matrix exponentiation

In [4]:
from scipy.linalg import expm, sinm, cosm
import numpy as np
# hadmard gate
h = np.array([[1.0, 1.0], [1.0, -1.0]])
expm(1j*h/np.sqrt(2)*np.pi/2)

array([[6.123234e-17+0.70710678j, 0.000000e+00+0.70710678j],
       [0.000000e+00+0.70710678j, 6.123234e-17-0.70710678j]])

## Solve matrix inverse

In [5]:
## solve A(4,3)*B(3,2)=C(4,2)
import numpy as np
from numpy.linalg import inv, matrix_rank, det
from numpy import dot, transpose
# np.set_printoptions(precision=5)

A = np.random.randn(4, 3)
C = np.random.randn(4, 2)
print(matrix_rank(A))
print('A=',A)
print('C=',C)
AT_A = dot(transpose(A),A)
print('AT_A=',AT_A)
print('rank of AT_A:',matrix_rank(AT_A))
A_left_inverse = dot(inv( AT_A ), transpose(A))
print(dot(inv( AT_A ), AT_A ))
print(dot(A,A_left_inverse))
B = dot(A_left_inverse, C)
print('B=',B)
# print(dot(A,dot(A_left_inverse, C)))
print('A*B=',dot(A,B))

3
A= [[ 0.89941201 -1.4702078   0.45367738]
 [-0.69002566  1.05551738  0.42235396]
 [-0.2899375   0.80970676 -1.70848919]
 [-0.66554943  0.83117547  0.90421768]]
C= [[ 0.65688558  0.12538482]
 [-0.57521043 -0.61011514]
 [ 1.80976455  0.40600328]
 [-0.71828868  2.94003704]]
AT_A= [[ 1.81209718 -2.83860935  0.01016134]
 [-2.83860935  4.62210563 -0.85300977]
 [ 0.01016134 -0.85300977  4.12075095]]
rank of AT_A: 3
[[ 1.00000000e+00 -1.91846539e-13  5.68434189e-14]
 [ 2.41473508e-13  1.00000000e+00  0.00000000e+00]
 [ 9.49240686e-15  2.66453526e-15  1.00000000e+00]]
[[ 0.65896721  0.03966072 -0.28152208 -0.37934387]
 [ 0.03966072  0.99538762  0.03273987  0.04411614]
 [-0.28152208  0.03273987  0.76760392 -0.31314782]
 [-0.37934387  0.04411614 -0.31314782  0.57804125]]
B= [[  6.18403603 -32.3004668 ]
 [  3.61563508 -20.09011768]
 [ -0.16138971  -3.65100197]]
A*B= [[ 0.17304252 -1.17115703]
 [-0.51894146 -0.45933262]
 [ 1.4103528  -0.66429018]
 [-1.2564859   1.49784376]]


In [6]:
a = np.array([[1., 2., 3.], [3., 5., 3.]])
aT_a = dot(transpose(a),a)
print(aT_a)
print(det(aT_a))
print('rank:',matrix_rank(aT_a))
ainv = inv(aT_a)
print(ainv)
np.allclose(dot(ainv, aT_a), np.eye(3))

[[10. 17. 12.]
 [17. 29. 21.]
 [12. 21. 18.]]
-3.197442310920468e-14
rank: 2
[[-2.53327479e+15  1.68884986e+15 -2.81474977e+14]
 [ 1.68884986e+15 -1.12589991e+15  1.87649984e+14]
 [-2.81474977e+14  1.87649984e+14 -3.12749974e+13]]


False