# Linear Algebra

### Perron–Frobenius theorem

````{prf:theorem} Perron–Frobenius theorem
:label: perron_frobenius_theorem
<!-- :class: dropdown -->

a real square matrix with positive entries has a unique largest real eigenvalue and that the corresponding eigenvector can be chosen to have strictly positive components, and also asserts a similar statement for certain classes of nonnegative matrices. 
````

## Matrix dot product

In [1]:
import numpy as np
from math import sqrt

U = np.matrix([[1/sqrt(2)+1j/2, -1j/2], 
              [1/2, 1/2+1j/sqrt(2)]])
X = np.matrix([[0,1],[1,0]])
Y = np.matrix([[0,-1j],[1j,0]])
Z = np.matrix([[1,0],[0,-1]])
# U.getH()
np.matmul(U,X)
print(np.matmul(U,X,U.H))
print(np.matmul(np.dot(U,X),U.getH()))
print(np.matmul(np.matmul(U,X),U.H))
print(np.dot(np.dot(U,X),U.getH()))
print(np.dot(np.dot(U,Y),U.getH()))
print(np.dot(np.dot(U,Z),U.getH()))

[[0.        -0.5j        0.70710678+0.5j       ]
 [0.5       +0.70710678j 0.5       +0.j        ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[ 7.07106781e-01+0.j          1.11022302e-16-0.70710678j]
 [ 1.11022302e-16+0.70710678j -7.07106781e-01+0.j        ]]
[[ 0.5       +0.j   0.70710678+0.5j]
 [ 0.70710678-0.5j -0.5       +0.j ]]


In [2]:
print(np.matmul(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [3]:
print(np.dot(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


## Matrix exponentiation

In [4]:
from scipy.linalg import expm, sinm, cosm
import numpy as np
# hadmard gate
h = np.array([[1.0, 1.0], [1.0, -1.0]])
expm(1j*h/np.sqrt(2)*np.pi/2)

array([[6.123234e-17+0.70710678j, 0.000000e+00+0.70710678j],
       [0.000000e+00+0.70710678j, 6.123234e-17-0.70710678j]])

## Solve matrix inverse

In [5]:
## solve A(4,3)*B(3,2)=C(4,2)
import numpy as np
from numpy.linalg import inv, matrix_rank, det
from numpy import dot, transpose
# np.set_printoptions(precision=5)

A = np.random.randn(4, 3)
C = np.random.randn(4, 2)
print(matrix_rank(A))
print('A=',A)
print('C=',C)
AT_A = dot(transpose(A),A)
print('AT_A=',AT_A)
print('rank of AT_A:',matrix_rank(AT_A))
A_left_inverse = dot(inv( AT_A ), transpose(A))
print(dot(inv( AT_A ), AT_A ))
print(dot(A,A_left_inverse))
B = dot(A_left_inverse, C)
print('B=',B)
# print(dot(A,dot(A_left_inverse, C)))
print('A*B=',dot(A,B))

3
A= [[-0.46417589 -1.0103691   0.12049983]
 [-0.12359076 -1.23638601  0.57175506]
 [ 0.07439373  3.24808134 -0.500522  ]
 [ 0.27763656 -0.28492676  0.68568294]]
C= [[-0.08675673 -0.67672474]
 [ 1.38154711 -1.21938846]
 [ 0.79368637  0.68750452]
 [ 0.80050688 -0.45627622]]
AT_A= [[ 0.31335042  0.78432568  0.02653819]
 [ 0.78432568 13.18071172 -2.64976484]
 [ 0.02653819 -2.64976484  1.06210742]]
rank of AT_A: 3
[[ 1.00000000e+00  8.88178420e-15 -1.77635684e-15]
 [ 3.46944695e-18  1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17 -1.77635684e-15  1.00000000e+00]]
[[ 0.78564498  0.34535068  0.0457525  -0.21690219]
 [ 0.34535068  0.44360017 -0.07371256  0.34945447]
 [ 0.0457525  -0.07371256  0.99023447  0.04629617]
 [-0.21690219  0.34945447  0.04629617  0.78052038]]
B= [[-1.32088776  1.47720561]
 [ 0.6355769  -0.04319503]
 [ 2.49529572 -1.49642841]]
A*B= [[ 0.27163969 -0.82235967]
 [ 0.80412909 -0.98475376]
 [ 0.7171893   0.71858922]
 [ 1.16316211 -0.60364173]]


In [6]:
a = np.array([[1., 2., 3.], [3., 5., 3.]])
aT_a = dot(transpose(a),a)
print(aT_a)
print(det(aT_a))
print('rank:',matrix_rank(aT_a))
ainv = inv(aT_a)
print(ainv)
np.allclose(dot(ainv, aT_a), np.eye(3))

[[10. 17. 12.]
 [17. 29. 21.]
 [12. 21. 18.]]
-3.197442310920468e-14
rank: 2
[[-2.53327479e+15  1.68884986e+15 -2.81474977e+14]
 [ 1.68884986e+15 -1.12589991e+15  1.87649984e+14]
 [-2.81474977e+14  1.87649984e+14 -3.12749974e+13]]


False