# Linear Algebra

## Matrix dot product

In [2]:
import numpy as np
from math import sqrt

U = np.matrix([[1/sqrt(2)+1j/2, -1j/2], 
              [1/2, 1/2+1j/sqrt(2)]])
X = np.matrix([[0,1],[1,0]])
Y = np.matrix([[0,-1j],[1j,0]])
Z = np.matrix([[1,0],[0,-1]])
# U.getH()
np.matmul(U,X)
print(np.matmul(U,X,U.H))
print(np.matmul(np.dot(U,X),U.getH()))
print(np.matmul(np.matmul(U,X),U.H))
print(np.dot(np.dot(U,X),U.getH()))
print(np.dot(np.dot(U,Y),U.getH()))
print(np.dot(np.dot(U,Z),U.getH()))

[[0.        -0.5j        0.70710678+0.5j       ]
 [0.5       +0.70710678j 0.5       +0.j        ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[ 7.07106781e-01+0.j          1.11022302e-16-0.70710678j]
 [ 1.11022302e-16+0.70710678j -7.07106781e-01+0.j        ]]
[[ 0.5       +0.j   0.70710678+0.5j]
 [ 0.70710678-0.5j -0.5       +0.j ]]


In [7]:
print(np.matmul(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [8]:
print(np.dot(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


## Matrix exponentiation

In [6]:
from scipy.linalg import expm, sinm, cosm
import numpy as np
# hadmard gate
h = np.array([[1.0, 1.0], [1.0, -1.0]])
expm(1j*h/np.sqrt(2)*np.pi/2)

array([[1.11022302e-16+0.70710678j, 0.00000000e+00+0.70710678j],
       [0.00000000e+00+0.70710678j, 0.00000000e+00-0.70710678j]])

## Solve matrix inverse

In [73]:
## solve A(4,3)*B(3,2)=C(4,2)
import numpy as np
from numpy.linalg import inv, matrix_rank, det
from numpy import dot, transpose
# np.set_printoptions(precision=5)

A = np.random.randn(4, 3)
C = np.random.randn(4, 2)
print(matrix_rank(A))
print('A=',A)
print('C=',C)
AT_A = dot(transpose(A),A)
print('AT_A=',AT_A)
print('rank of AT_A:',matrix_rank(AT_A))
A_left_inverse = dot(inv( AT_A ), transpose(A))
print(dot(inv( AT_A ), AT_A ))
print(dot(A,A_left_inverse))
B = dot(A_left_inverse, C)
print('B=',B)
# print(dot(A,dot(A_left_inverse, C)))
print('A*B=',dot(A,B))

3
A= [[-1.31258 -0.26481 -0.10199]
 [-0.33874  0.67585 -0.75528]
 [-0.52218  2.20508  0.06103]
 [ 0.71301  0.21345  1.33031]]
C= [[-0.49183 -2.31241]
 [ 0.68963 -0.21984]
 [-0.00886  1.04072]
 [-0.25031 -1.66598]]
AT_A= [[ 2.61866 -0.8806   1.30636]
 [-0.8806   5.43483 -0.0649 ]
 [ 1.30636 -0.0649   2.3543 ]]
rank of AT_A: 3
[[ 1.00000e+00  1.04083e-17  0.00000e+00]
 [ 0.00000e+00  1.00000e+00  1.38778e-17]
 [-1.11022e-16  0.00000e+00  1.00000e+00]]
[[ 0.97292 -0.13367  0.04547 -0.08005]
 [-0.13367  0.3401   0.22446 -0.3952 ]
 [ 0.04547  0.22446  0.92365  0.13442]
 [-0.08005 -0.3952   0.13442  0.76332]]
B= [[ 0.4325   1.541  ]
 [ 0.15948  0.67297]
 [-0.5772  -1.58021]]
A*B= [[-0.55106 -2.03973]
 [ 0.39722  1.12633]
 [ 0.0906   0.58283]
 [-0.42543 -0.85979]]


In [65]:
a = np.array([[1., 2., 3.], [3., 5., 3.]])
aT_a = dot(transpose(a),a)
print(aT_a)
print(det(aT_a))
print('rank:',matrix_rank(aT_a))
ainv = inv(aT_a)
print(ainv)
np.allclose(dot(ainv, aT_a), np.eye(3))

[[10. 17. 12.]
 [17. 29. 21.]
 [12. 21. 18.]]
-2.498001805406606e-14
rank: 2
[[-3.24259173e+15  2.16172782e+15 -3.60287970e+14]
 [ 2.16172782e+15 -1.44115188e+15  2.40191980e+14]
 [-3.60287970e+14  2.40191980e+14 -4.00319967e+13]]


False