# Cholesky decomposition

## Statement

The Cholesky decomposition of a Hermitian positive-definite matrix $A$, is a decomposition of the form

$$A=LL^\dagger$$

where $L$ is a lower triangular matrix with real and positive diagonal entries, and $L^\dagger$ denotes the conjugate transpose of $L$.

````{prf:theorem} Orthogonal-Projection-Theorem
:label: my-theorem
:class: dropdown

Given $y \in \mathbb R^n$ and linear subspace $S \subset \mathbb R^n$,
there exists a unique solution to the minimization problem

```{math}
\hat y := \argmin_{z \in S} \|y - z\|
```

The minimizer $\hat y$ is the unique vector in $\mathbb R^n$ that satisfies

* $\hat y \in S$

* $y - \hat y \perp S$


The vector $\hat y$ is called the **orthogonal projection** of $y$ onto $S$.
````
<!-- https://sphinx-proof.readthedocs.io/en/latest/syntax.html#how-to-hide-content -->

## Proof

### numerical solution of linear equations

### Proof for positive semi-definite matrices

### Proof by QR decomposition


## The algorithm

## Efficiency

## Applications


### Monte Carlo simulation

### Matrix inversion

In [1]:
## solve A(4,3)*B(3,2)=C(4,2)
import numpy as np
from numpy.linalg import inv, matrix_rank, det
from numpy import dot, transpose


In [65]:
a = np.array([[1., 2., 3.], [3., 5., 3.]])
aT_a = dot(transpose(a),a)
print(aT_a)
print(det(aT_a))
print('rank:',matrix_rank(aT_a))
ainv = inv(aT_a)
print(ainv)
np.allclose(dot(ainv, aT_a), np.eye(3))

[[10. 17. 12.]
 [17. 29. 21.]
 [12. 21. 18.]]
-2.498001805406606e-14
rank: 2
[[-3.24259173e+15  2.16172782e+15 -3.60287970e+14]
 [ 2.16172782e+15 -1.44115188e+15  2.40191980e+14]
 [-3.60287970e+14  2.40191980e+14 -4.00319967e+13]]


False