# Linear Algebra

## Matrix dot product

In [1]:
import numpy as np
from math import sqrt

U = np.matrix([[1/sqrt(2)+1j/2, -1j/2], 
              [1/2, 1/2+1j/sqrt(2)]])
X = np.matrix([[0,1],[1,0]])
Y = np.matrix([[0,-1j],[1j,0]])
Z = np.matrix([[1,0],[0,-1]])
# U.getH()
np.matmul(U,X)
print(np.matmul(U,X,U.H))
print(np.matmul(np.dot(U,X),U.getH()))
print(np.matmul(np.matmul(U,X),U.H))
print(np.dot(np.dot(U,X),U.getH()))
print(np.dot(np.dot(U,Y),U.getH()))
print(np.dot(np.dot(U,Z),U.getH()))

[[0.        -0.5j        0.70710678+0.5j       ]
 [0.5       +0.70710678j 0.5       +0.j        ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[-0.5       +0.j   0.70710678-0.5j]
 [ 0.70710678+0.5j  0.5       +0.j ]]
[[ 7.07106781e-01+0.j          1.11022302e-16-0.70710678j]
 [ 1.11022302e-16+0.70710678j -7.07106781e-01+0.j        ]]
[[ 0.5       +0.j   0.70710678+0.5j]
 [ 0.70710678-0.5j -0.5       +0.j ]]


In [2]:
print(np.matmul(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [3]:
print(np.dot(U,U.getH()))

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


## Matrix exponentiation

In [4]:
from scipy.linalg import expm, sinm, cosm
import numpy as np
# hadmard gate
h = np.array([[1.0, 1.0], [1.0, -1.0]])
expm(1j*h/np.sqrt(2)*np.pi/2)

array([[ 3.23420673e-17+0.70710678j,  3.23420673e-17+0.70710678j],
       [-3.58447001e-18+0.70710678j,  4.67208659e-17-0.70710678j]])

## Solve matrix inverse

In [5]:
## solve A(4,3)*B(3,2)=C(4,2)
import numpy as np
from numpy.linalg import inv, matrix_rank, det
from numpy import dot, transpose
# np.set_printoptions(precision=5)

A = np.random.randn(4, 3)
C = np.random.randn(4, 2)
print(matrix_rank(A))
print('A=',A)
print('C=',C)
AT_A = dot(transpose(A),A)
print('AT_A=',AT_A)
print('rank of AT_A:',matrix_rank(AT_A))
A_left_inverse = dot(inv( AT_A ), transpose(A))
print(dot(inv( AT_A ), AT_A ))
print(dot(A,A_left_inverse))
B = dot(A_left_inverse, C)
print('B=',B)
# print(dot(A,dot(A_left_inverse, C)))
print('A*B=',dot(A,B))

3
A= [[ 0.79648474  0.5780258  -0.33075085]
 [ 1.538182    0.23909315 -1.62163833]
 [ 0.47046309  1.21970173 -1.34628455]
 [ 0.92591459  0.76067829  1.03810765]]
C= [[-0.72190386 -0.15203383]
 [ 0.90054997 -2.22046253]
 [-0.5246409   1.484859  ]
 [ 0.36335175  1.14780657]]
AT_A= [[ 4.07904516  2.10630526 -2.42999106]
 [ 2.10630526  2.45758313 -1.43130479]
 [-2.42999106 -1.43130479  5.6292566 ]]
rank of AT_A: 3
[[ 1.00000000e+00 -2.77555756e-16  2.22044605e-16]
 [ 1.38777878e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 0.18238259  0.20191363  0.17340166  0.27978909]
 [ 0.20191363  0.95013669 -0.04282218 -0.06909495]
 [ 0.17340166 -0.04282218  0.96322469 -0.05933814]
 [ 0.27978909 -0.06909495 -0.05933814  0.90425603]]
B= [[ 0.64263138 -1.28309235]
 [-0.7437273   2.24404149]
 [ 0.06377506  0.52184171]]
A*B= [[ 0.06085886  0.1025508 ]
 [ 0.70724383 -2.28333314]
 [-0.69065052  1.43086627]
 [ 0.09548995  1.06068758]]


In [6]:
a = np.array([[1., 2., 3.], [3., 5., 3.]])
aT_a = dot(transpose(a),a)
print(aT_a)
print(det(aT_a))
print('rank:',matrix_rank(aT_a))
ainv = inv(aT_a)
print(ainv)
np.allclose(dot(ainv, aT_a), np.eye(3))

[[10. 17. 12.]
 [17. 29. 21.]
 [12. 21. 18.]]
-2.498001805406606e-14
rank: 2
[[-3.24259173e+15  2.16172782e+15 -3.60287970e+14]
 [ 2.16172782e+15 -1.44115188e+15  2.40191980e+14]
 [-3.60287970e+14  2.40191980e+14 -4.00319967e+13]]


False